const khodamlist = [
  "macan putih",
  "macan lapar",
  "macan tidur",
  "kuda putih",
  "kuda laut",
  "tuyul mulet",
  "kulkas",
  "titid terbang",
  "genderuwo",
  "pocong salto",
  "kuyang",
  "plastik",
  "gajah terbang",
  "kuda pony",
  "le mineral",
  "topi koki",
  "wortel",
  "daging kurban",
  "kuntilanak",
  "sundel bolong",
  "banaspati",
  "kwetiaw",
  "ayam kampung",
  "ayam potong",
  "ayam kampus",
  "kompor gas",
  "kucing",
  "firaun",
  "ular",
  "dinosaurus",
  "platipus",
  "bebek nungging",
  "lebah ganteng",
  "pein akatsuki",
  "tidak ada",
  "naga terbang",
  "jenglot",
  "harimau kumbang",
  "elang laut",
  "kucing oren",
  "pocong lompat-lompat",
  "suster ngesot",
  "cecak ninja",
  "babi ngepet",
  "cacing tanah raksasa",
  "ular naga",
  "burung hantu",
  "orang minyak",
  "buto ijo",
  "wong gede",
  "ikan duyung",
  "kura-kura ninja",
  "hiu darat",
  "tuyul joget",
  "ninja hatori",
  "ular terbang",
  "anjing kampung",
  "semut merah",
  "belalang tempur",
  "gorila ngamuk",
  "manusia karet",
  "gundala petir",
  "badak bercula tiga",
  "burung cendrawasih",
  "katak ninja",
  "manusia api",
  "raja jin",
  "monyet sakti",
  "harimau sirkus",
  "tengkorak hidup",
  "robot penghancur",
  "alien berkepala dua",
  "kucing meong",
  "panda bersayap",
  "zombie dancer",
  "semar mesem",
  "garuda putih",
  "macan hijau",
  "macan emas",
  "naga hitam",
  "serigala malam",
  "beruang kutub",
  "kerbau putih",
  "ikan paus kecil",
  "lele sakti",
  "laba-laba raksasa",
  "capung emas",
  "penunggu pohon beringin",
  "srigala api",
  "kera putih",
  "lumba-lumba sakti",
  "jaka sembung",
  "bidadari laut",
  "ratu pantai selatan",
  "nyai ronggeng",
  "jaka tarub",
  "manusia serigala",
  "ikan mas sakti",
  "kebo bule",
  "lele jumbo",
  "pinguin ninja",
  "kucing ungu",
];

function pilihkhodam(event) {
  event.preventDefault();
  const nama = document.getElementById("nama").value;
  const resultDiv = document.getElementById("result");
  resultDiv.textContent = "";
  if (nama) {
    const randomIndex = Math.floor(Math.random() * khodamlist.length);
    const khodamTerpilih = khodamlist[randomIndex];
    resultDiv.textContent = `khodam ${nama} adalah ${khodamTerpilih}.`;

    setTimeout(() => {
      resultDiv.textContent = "";
    }, 5000);
  } else {
    resultDiv.textContent = "nama tidak boleh kosong.";
  }
}
document.getElementById("khodamForm").addEventListener("submit", pilihkhodam);
